name: Generate and publish document

on:
  push:
    branches:
      - main

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./cv
          root_file: cv_felix_hoffmann.tex
          args: -pdf -synctex=1 -shell-escape -interaction=nonstopmode -output-directory=out
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: cv/out/cv_felix_hoffmann.pdf
